
package fr.afcepf.atod.onwine.ws.soap.tax;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceTax", targetNamespace = "http://tax.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceTax {


    /**
     * 
     * @param codePays
     * @param montant
     * @return
     *     returns java.lang.Double
     * @throws TaxWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculTax", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.CalculTax")
    @ResponseWrapper(localName = "calculTaxResponse", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.CalculTaxResponse")
    public Double calculTax(
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "codePays", targetNamespace = "")
        String codePays)
        throws TaxWSException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.atod.onwine.ws.soap.tax.TaxDto>
     * @throws TaxWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCountryTax", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.GetAllCountryTax")
    @ResponseWrapper(localName = "getAllCountryTaxResponse", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.GetAllCountryTaxResponse")
    public List<TaxDto> getAllCountryTax()
        throws TaxWSException_Exception
    ;

    /**
     * 
     * @param codePays
     * @return
     *     returns fr.afcepf.atod.onwine.ws.soap.tax.TaxDto
     * @throws TaxWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rechercherTax", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.RechercherTax")
    @ResponseWrapper(localName = "rechercherTaxResponse", targetNamespace = "http://tax.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.tax.RechercherTaxResponse")
    public TaxDto rechercherTax(
        @WebParam(name = "codePays", targetNamespace = "")
        String codePays)
        throws TaxWSException_Exception
    ;

}
