
package fr.afcepf.atod.onwine.ws.soap.tax;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "TaxWSException", targetNamespace = "http://tax.afcepf.fr")
public class TaxWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TaxWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TaxWSException_Exception(String message, TaxWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TaxWSException_Exception(String message, TaxWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.atod.onwine.ws.soap.tax.TaxWSException
     */
    public TaxWSException getFaultInfo() {
        return faultInfo;
    }

}
