
package fr.afcepf.atod.onwine.ws.soap.delivery;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DeliveriesWSException", targetNamespace = "http://delivery.afcepf.fr")
public class DeliveriesWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DeliveriesWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DeliveriesWSException_Exception(String message, DeliveriesWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DeliveriesWSException_Exception(String message, DeliveriesWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.afcepf.atod.onwine.ws.soap.delivery.DeliveriesWSException
     */
    public DeliveriesWSException getFaultInfo() {
        return faultInfo;
    }

}
