
package fr.afcepf.atod.onwine.ws.soap.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DeliveryCalculatorService", targetNamespace = "http://delivery.afcepf.fr", wsdlLocation = "http://192.168.102.42:8180/OnWine-DeliveryWS-Biz/DeliveryCalculator?wsdl")
public class DeliveryCalculatorService
    extends Service
{

    private final static URL DELIVERYCALCULATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.afcepf.atod.onwine.ws.soap.delivery.DeliveryCalculatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.afcepf.atod.onwine.ws.soap.delivery.DeliveryCalculatorService.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.102.42:8180/OnWine-DeliveryWS-Biz/DeliveryCalculator?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.102.42:8180/OnWine-DeliveryWS-Biz/DeliveryCalculator?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DELIVERYCALCULATORSERVICE_WSDL_LOCATION = url;
    }

    public DeliveryCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryCalculatorService() {
        super(DELIVERYCALCULATORSERVICE_WSDL_LOCATION, new QName("http://delivery.afcepf.fr", "DeliveryCalculatorService"));
    }

    /**
     * 
     * @return
     *     returns IDeliveryCalculator
     */
    @WebEndpoint(name = "DeliveryCalculatorPort")
    public IDeliveryCalculator getDeliveryCalculatorPort() {
        return super.getPort(new QName("http://delivery.afcepf.fr", "DeliveryCalculatorPort"), IDeliveryCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDeliveryCalculator
     */
    @WebEndpoint(name = "DeliveryCalculatorPort")
    public IDeliveryCalculator getDeliveryCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://delivery.afcepf.fr", "DeliveryCalculatorPort"), IDeliveryCalculator.class, features);
    }

}
