
package fr.afcepf.atod.onwine.ws.soap.delivery;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IDeliveryCalculator", targetNamespace = "http://delivery.afcepf.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDeliveryCalculator {


    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.atod.onwine.ws.soap.delivery.DtDelivery>
     * @throws DeliveriesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDeliveries", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetAllDeliveries")
    @ResponseWrapper(localName = "getAllDeliveriesResponse", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetAllDeliveriesResponse")
    public List<DtDelivery> getAllDeliveries()
        throws DeliveriesWSException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     * @throws DeliveriesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRateDeliveryTotal", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetRateDeliveryTotal")
    @ResponseWrapper(localName = "getRateDeliveryTotalResponse", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetRateDeliveryTotalResponse")
    public Double getRateDeliveryTotal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws DeliveriesWSException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     * @throws DeliveriesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInternationalRateDelivery", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetInternationalRateDelivery")
    @ResponseWrapper(localName = "getInternationalRateDeliveryResponse", targetNamespace = "http://delivery.afcepf.fr", className = "fr.afcepf.atod.onwine.ws.soap.delivery.GetInternationalRateDeliveryResponse")
    public Double getInternationalRateDelivery(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws DeliveriesWSException_Exception
    ;

}
