
package fr.afcepf.atod.onwine.ws.soap.currency;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICurrencyConverter", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICurrencyConverter {


    /**
     * 
     * @param amount
     * @param src
     * @param trgt
     * @return
     *     returns java.lang.Double
     * @throws CurrenciesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.ConvertResponse")
    public Double convert(
        @WebParam(name = "amount", targetNamespace = "")
        Double amount,
        @WebParam(name = "src", targetNamespace = "")
        String src,
        @WebParam(name = "trgt", targetNamespace = "")
        String trgt)
        throws CurrenciesWSException_Exception
    ;

    /**
     * 
     * @param amount
     * @param src
     * @param trgt
     * @return
     *     returns fr.afcepf.atod.onwine.ws.soap.currency.Wrapper
     * @throws CurrenciesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertAndFormat", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.ConvertAndFormat")
    @ResponseWrapper(localName = "convertAndFormatResponse", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.ConvertAndFormatResponse")
    public Wrapper convertAndFormat(
        @WebParam(name = "amount", targetNamespace = "")
        Double amount,
        @WebParam(name = "src", targetNamespace = "")
        String src,
        @WebParam(name = "trgt", targetNamespace = "")
        String trgt)
        throws CurrenciesWSException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<fr.afcepf.atod.onwine.ws.soap.currency.DtCurrency>
     * @throws CurrenciesWSException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCurrencies", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.GetAllCurrencies")
    @ResponseWrapper(localName = "getAllCurrenciesResponse", targetNamespace = "http://soap.currency.ws.atod.afcepf.fr/", className = "fr.afcepf.atod.onwine.ws.soap.currency.GetAllCurrenciesResponse")
    public List<DtCurrency> getAllCurrencies()
        throws CurrenciesWSException_Exception
    ;

}
