
package fr.afcepf.atod.onwine.ws.soap.orchestre;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "OnWineServicesOrchestrator", targetNamespace = "http://orchestrateur.onwine.atod.afcepf.fr", wsdlLocation = "http://192.168.102.67:9090/ode/processes/OnWineServicesOrchestrator?wsdl")
public class OnWineServicesOrchestrator
    extends Service
{

    private final static URL ONWINESERVICESORCHESTRATOR_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(fr.afcepf.atod.onwine.ws.soap.orchestre.OnWineServicesOrchestrator.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = fr.afcepf.atod.onwine.ws.soap.orchestre.OnWineServicesOrchestrator.class.getResource(".");
            url = new URL(baseUrl, "http://192.168.102.67:9090/ode/processes/OnWineServicesOrchestrator?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.102.67:9090/ode/processes/OnWineServicesOrchestrator?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ONWINESERVICESORCHESTRATOR_WSDL_LOCATION = url;
    }

    public OnWineServicesOrchestrator(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnWineServicesOrchestrator() {
        super(ONWINESERVICESORCHESTRATOR_WSDL_LOCATION, new QName("http://orchestrateur.onwine.atod.afcepf.fr", "OnWineServicesOrchestrator"));
    }

    /**
     * 
     * @return
     *     returns OnWineServicesOrchestratorPortType
     */
    @WebEndpoint(name = "OnWineServicesOrchestratorPort")
    public OnWineServicesOrchestratorPortType getOnWineServicesOrchestratorPort() {
        return super.getPort(new QName("http://orchestrateur.onwine.atod.afcepf.fr", "OnWineServicesOrchestratorPort"), OnWineServicesOrchestratorPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnWineServicesOrchestratorPortType
     */
    @WebEndpoint(name = "OnWineServicesOrchestratorPort")
    public OnWineServicesOrchestratorPortType getOnWineServicesOrchestratorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://orchestrateur.onwine.atod.afcepf.fr", "OnWineServicesOrchestratorPort"), OnWineServicesOrchestratorPortType.class, features);
    }

}
