
package fr.afcepf.atod.onwine.ws.soap.orchestre;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "OnWineServicesOrchestratorPortType", targetNamespace = "http://orchestrateur.onwine.atod.afcepf.fr")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnWineServicesOrchestratorPortType {


    /**
     * 
     * @param payload
     * @return
     *     returns fr.afcepf.atod.onwine.ws.soap.orchestre.OnWineServicesOrchestratorResponse
     */
    @WebMethod(action = "http://orchestrateur.onwine.atod.afcepf.fr/process")
    @WebResult(name = "OnWineServicesOrchestratorResponse", targetNamespace = "http://orchestrateur.onwine.atod.afcepf.fr", partName = "payload")
    public OnWineServicesOrchestratorResponse process(
        @WebParam(name = "OnWineServicesOrchestratorRequest", targetNamespace = "http://orchestrateur.onwine.atod.afcepf.fr", partName = "payload")
        OnWineServicesOrchestratorRequest payload);

}
